# Generated by Django 3.2.15 on 2024-10-15 05:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_on', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_on', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('file', models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'zip'])])),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('ground_truth', models.JSONField(blank=True, default=dict, null=True)),
                ('created_on', models.CharField(blank=True, db_index=True, max_length=100)),
                ('thumbnail', models.ImageField(blank=True, editable=False, null=True, upload_to='thumbs')),
                ('config_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ObligationFlowApp.config')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ManyToManyField(blank=True, to='ObligationFlowApp.Folder')),
            ],
        ),
    ]
