# Generated by Django 3.2.15 on 2024-10-15 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ObligationFlowApp', '0002_auto_20241015_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='contract_model',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='vendor',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='SingleApiCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('apifile', models.FileField(upload_to='documents/')),
                ('result', models.JSONField(blank=True, default=dict, null=True)),
                ('config_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ObligationFlowApp.config')),
            ],
        ),
    ]
