# Generated by Django 3.2.15 on 2024-10-17 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ObligationFlowApp', '0003_auto_20241015_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleapicall',
            name='apifile',
        ),
    ]
