# Generated by Django 3.2.15 on 2024-10-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObligationFlowApp', '0004_remove_singleapicall_apifile'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleapicall',
            name='apifile',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
