# Generated by Django 5.1.2 on 2024-10-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObligationFlowApp', '0005_singleapicall_apifile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('extracted_terms', models.JSONField(blank=True, default=dict, null=True)),
                ('extracted_clauses', models.JSONField(blank=True, default=dict, null=True)),
                ('extracted_obligations', models.JSONField(blank=True, default=dict, null=True)),
                ('extracted_contract_type', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='config_name',
        ),
        migrations.RemoveField(
            model_name='singleapicall',
            name='config_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='contract_model',
        ),
        migrations.RemoveField(
            model_name='document',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.DeleteModel(
            name='SingleApiCall',
        ),
    ]
