# Generated by Django 5.1.2 on 2024-10-28 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObligationFlowApp', '0007_document_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['docx'])]),
        ),
        migrations.AlterField(
            model_name='documentresponse',
            name='extracted_contract_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
