# Generated by Django 5.1.2 on 2024-11-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObligationFlowApp', '0009_obligationmetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentresponse',
            name='extracted_contract_type',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
