# Generated by Django 5.1.2 on 2024-11-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObligationFlowApp', '0010_alter_documentresponse_extracted_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='obligationmetadata',
            name='suggestions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
