# Generated by Django 5.1.2 on 2024-11-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObligationFlowApp', '0011_obligationmetadata_suggestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskTrackingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('review_frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], max_length=20)),
                ('risk_mitigation_plan', models.TextField()),
                ('responsible_parties', models.CharField(max_length=255)),
                ('email_notifications', models.BooleanField(default=True)),
                ('system_notifications', models.BooleanField(default=True)),
            ],
        ),
    ]
