# Generated by Django 5.1.2 on 2024-11-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObligationFlowApp', '0012_risktrackingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='risktrackingrecord',
            name='document_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='risktrackingrecord',
            name='obligation_id',
            field=models.IntegerField(null=True),
        ),
    ]
