# Generated by Django 5.1.2 on 2024-11-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObligationFlowApp', '0014_risktrackingrecord_ai_trigger_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risktrackingrecord',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='risktrackingrecord',
            name='status',
            field=models.CharField(choices=[('init', 'Init'), ('ongoing', 'Ongoing'), ('executed', 'Executed'), ('cancelled', 'Cancelled')], max_length=20, null=True),
        ),
    ]
