# Generated by Django 5.1.2 on 2024-11-16 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObligationFlowApp', '0015_risktrackingrecord_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risktrackingrecord',
            name='ai_trigger_condition',
            field=models.TextField(default='No conditon provided as of now'),
        ),
        migrations.AlterField(
            model_name='risktrackingrecord',
            name='document_id',
            field=models.IntegerField(default=86),
        ),
        migrations.AlterField(
            model_name='risktrackingrecord',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='risktrackingrecord',
            name='obligation_id',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='risktrackingrecord',
            name='status',
            field=models.CharField(choices=[('init', 'Init'), ('ongoing', 'Ongoing'), ('executed', 'Executed'), ('cancelled', 'Cancelled')], default='init', max_length=20),
        ),
    ]
