# Generated by Django 5.1.2 on 2024-11-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObligationFlowApp', '0016_alter_risktrackingrecord_ai_trigger_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risktrackingrecord',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
    ]
