# Generated by Django 5.1.2 on 2024-11-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObligationFlowApp', '0017_risktrackingrecord_is_cancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risktrackingrecord',
            name='is_cancel',
            field=models.BooleanField(default=True),
        ),
    ]
