# Generated by Django 5.1.2 on 2024-11-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObligationFlowApp', '0019_alter_risktrackingrecord_is_cancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risktrackingrecord',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
