# Generated by Django 5.1.2 on 2024-11-18 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObligationFlowApp', '0020_alter_risktrackingrecord_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('risk_tracking_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ObligationFlowApp.risktrackingrecord')),
            ],
        ),
    ]
