# Generated by Django 5.1.2 on 2024-11-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ObligationFlowApp', '0021_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risktrackingrecord',
            name='end_date',
            field=models.DateField(),
        ),
    ]
